[workspace]
resolver = "2"
members = ["polenta", "cli", "tui"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["erhant"]
license = "MIT"

[workspace.dependencies]
lambdaworks-math = { version = "0.7.0" }
