[package]
name = "polenta"
version = "0.1.0"
edition = "2021"
authors = ["erhant"]
license = "MIT"

[dependencies]
lambdaworks-math = "0.7.0"
lazy_static = "1.5.0"
pest = "2.7.10"
pest_derive = "2.7.10"
