[package]
name = "polenta-cli"
version.workspace = true
edition.workspace = true

[dependencies]
polenta = { path = "../polenta" }
lambdaworks-math.workspace = true
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.63"
colored = "2.1.0"
rustyline = "14.0.0"
